### ISSUE TITLE
Creating election wizard UI design

### ISSUE THREAD

**Issue by YujithIsura** [ECLK/Nomination-UI#12]
Step 1
![screenshot from 2019-01-16 11-38-03](https://user-images.githubusercontent.com/42527969/51229676-38734780-1983-11e9-85f9-a97fe1422f63.png)
This check boxes in each two sections should be iterated by an array

Step 2
by clicking the plus icon user should be able to add a new line and when user press on delete icon that line should be deleted
![screenshot from 2019-01-16 11-31-39](https://user-images.githubusercontent.com/42527969/51229606-fc3fe700-1982-11e9-96b9-98ef01a9412e.png)

Step 3
![screenshot from 2019-01-16 11-39-21](https://user-images.githubusercontent.com/42527969/51229743-740e1180-1983-11e9-94f7-848a55529b14.png)

Todo : Design above pages using react+meterialUI stepper and place it here "src/pages/ADMIN/Election-config"

#### Back-end APIs
1. Field Options API to cater **candidate form config** & **supporting documents** & ** Eligibility Checklist**
/options/{fild-name}
returns 
```
[
{ key:"", label:"", type: "boolean" }
]
```

2. Election Module Structure
```
{
    name: "Provincial",
    id: "uuid",
    candidateFormConfiguration: [
       // field key's which are true.
    ],
    supportingDocuments: [

    ],
    division:[
         { commonName:"Provintial" , divisionName:"Name", divisionCode:"01", noOfCandidates: 67 },
         ...
    ],
    electionConfig:{
        authority: "",
        calculationType: "",
        ...
    },
    eligibilityConfig: [
        // set of keys selected.
    ]
}
```

**Comment by hevayo** [comment]
I'll work on this
