### ISSUE TITLE
Election process review UI design

### ISSUE THREAD

**Issue by YujithIsura** [ECLK/Nomination-UI#13]
![screenshot from 2019-01-16 12-04-21](https://user-images.githubusercontent.com/42527969/51230735-1d0a3b80-1987-11e9-84ed-c58582dec36b.png)

Above figure shows the Election process home interface. Here shows the cards of active elections. This card should be iterated by an array 
When user clicks on a particular card the user will be redirected to the following interface. Which will shows the all details of a particular election.

![screenshot from 2019-01-16 12-05-00](https://user-images.githubusercontent.com/42527969/51230860-7b371e80-1987-11e9-84df-fd1c68fbd390.png)

Todo : Design above pages in react+meterialUI and place it here "src/pages/ADMIN/Election-review"
           you are allowed to use suitable designs for above interfaces 

```
related endpoints
18) get: election/
Description: get active elections

Return:{
   "election_id":"32d250c8-b6b0-4aa6-9b14-4817dbb268d9",
   "election_name":"e1_Parliamentary",
}
19) get: /election/:election_id
Description: get a particular election

Return-parameters:{
   "election_id":"32d250c8-b6b0-4aa6-9b14-4817dbb268d9",
   "election_name":"e1_Parliamentary",
   "election_module_id":"32d250c8-b6b0-4aa6-9b1",
   "authority":"Election admin",
   "calculation_type":"Pure vote-based|Pure preference-based
|Vote & Preferential -based ",
   "weightage_vote":"75",
   "weightage_preference":"25",
   "Can_submit":"part secretary|IG leader",
   "Deposite_payment":"yes|no",
   "payment_amount_per_nominee":"1500.00",
   "Nomination_start":"2018-12-10",
   "Nomination_end":"2018-12-25",
   "objection_availability":"Allowed | Not Allowed",
   "Objection_start":"32d250c8-b6b0-4aa6-9b14-4817dbb268d9",
   "objection_end":"e1_Parliamentary",
   "election_status":"Pending",
Eligibility:{
 Eligibility_id:"32d250c8-b6b0-4aa6-9b14-4817dbb268d9",   
}
}    
20) put: election/:election_id
Description: update election status

Required-parameters:{
"status":"Approved|Rejected",  
}

```

**Comment by asela-wijesinghe** [comment]
on it :)

**Comment by asela-wijesinghe** [comment]
UI's Ready please merge **https://github.com/ECLK/Nomination-UI/pull/59**

![screenshot from 2019-02-27 16-20-14](https://user-images.githubusercontent.com/23404276/53485549-79936700-3aac-11e9-8d84-a67eb48d5788.png)
![screenshot from 2019-02-27 16-20-29](https://user-images.githubusercontent.com/23404276/53485551-7b5d2a80-3aac-11e9-9075-cca29b32bcfb.png)

**Comment by YujithIsura** [comment]
Merged.. thanks asela
